# Generated by Django 4.2.16 on 2024-10-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='user.users'),
        ),
    ]
